import ThemeProvider from "@/components/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const chirp = localFont({
  src: [
    {
      path: "./fonts/chirp-bold-web.woff",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/chirp-bold-web.woff2",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/chirp-extended-heavy-web.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/chirp-extended-heavy-web.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/chirp-heavy-web.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/chirp-heavy-web.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/chirp-regular-web.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/chirp-regular-web.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${chirp.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
